[project]
name = "django-otel-lamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-prometheus>=2.3.1",
    "django>=5.2",
    "pytest-django>=4.11.1",
    "requests>=2.32.3",
]
