name: First GH action in a while
on: push
jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'Hello'"
      - uses: "actions/checkout@v4"
      - run: "ls"
      - run: "pip"
      - name: Installing uv
        run: "curl -LsSf https://astral.sh/uv/install.sh | sh"
      - run: "uv sync"
      - run: "uv run pytest test.py"

